/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ac.umons;

public class TestWindowing {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new TestWindowing().getGreeting());
    }
}
