/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ac.umons;

import be.ac.umons.frontend.WindowingController;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class TestWindowing extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        WindowingController controller = new WindowingController(primaryStage);
        Scene scene = new Scene(controller.buildUI(), 950, 580);
        primaryStage.setTitle("Windowing — Priority Search Tree");
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
