/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ac.umons;

import be.ac.umons.frontend.WindowingController;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.stage.Stage;

/**
 * Entry point of the windowing application.
 * Launches a JavaFX window that visualizes axis-aligned segments using a Priority Search Tree.
 */
public class TestWindowing extends Application {

    /**
     * Launches the JavaFX application.
     *
     * @param args command-line arguments passed to the application
     */
    public static void main(String[] args) {
        launch(args);
    }

    /**
     * Initializes and displays the primary stage.
     * Builds the UI via WindowingController, applies the stylesheet, and shows the window.
     *
     * @param primaryStage the primary stage provided by the JavaFX runtime
     * @throws Exception if the stylesheet resource cannot be loaded
     */
    @Override
    public void start(Stage primaryStage) throws Exception {
        WindowingController controller = new WindowingController(primaryStage);
        Scene scene = new Scene(controller.buildUI(), 950, 580);
        scene.getStylesheets().add(getClass().getResource("/be/ac/umons/frontend/style.css").toExternalForm());
        primaryStage.setTitle("Windowing — Priority Search Tree");
        primaryStage.setScene(scene);
        primaryStage.show();
    }
}
