/*
 * This source file was generated by the Gradle 'init' task
 */
package be.ac.umons;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class AppTest {
    @Test void appHasAGreeting() {
        TestWindowing classUnderTest = new TestWindowing();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
